In [1]:
import pandas as pd
import numpy as np
import re
from matplotlib import pyplot as plt

import matplotlib.pyplot as plt

pd.set_option('max.columns', None)

# Import Data

## Import results file

In [2]:
results = pd.read_csv('results.csv', index_col = 0)

results = results[['row', 'plc', 'horseno', 'horse', 'jockey', 'trainer', 'actualwt',
       'declarwt', 'draw', 'lbw', 'runningpos', 'finishtime', 'winodds',
       'date', 'raceno', 'class', 'distance', 'going', 'handicap', 'course',
       'stake', 'venue']]

results.head()

,row,plc,horseno,horse,jockey,trainer,actualwt,declarwt,draw,lbw,runningpos,finishtime,winodds,date,raceno,class,distance,going,handicap,course,stake,venue
0,0,1,10.0,NATURAL EIGHT(S243),C Y Ho,C Fownes,119.0,1037.0,1.0,-,4 3 1,1.10.19,3.5,2015-06-03,1,5,1200,GOOD TO FIRM,MOUNT BUTLER HANDICAP,TURF - A COURSE,575000,Happy Valley
1,0,1,7.0,SOLAR HEI HEI(T242),B Prebble,D J Hall,125.0,1077.0,11.0,-,9 8 1,1.09.06,2.3,2015-06-07,1,4,1200,GOOD TO FIRM,HKU FOUNDATION HANDICAP,TURF - A+3 COURSE,760000,Sha Tin
2,0,1,3.0,GRAN BOLIVAR(S165),H N Wong,Y S Tsui,121.0,950.0,9.0,-,1 1 1,1.09.64,32.0,2015-06-10,1,4,1200,GOOD TO FIRM,LAI ON HANDICAP,TURF - B COURSE,760000,Happy Valley
3,0,1,11.0,PEOPLE'S KNIGHT(T305),G Mosse,J Moore,120.0,1149.0,4.0,-,4 4 1,1.09.70,6.6,2015-06-14,1,1,1200,GOOD TO FIRM,BREGUET PLATE,TURF - B+2 COURSE,800000,Sha Tin
4,0,1,2.0,SIR JOHN(P344),B Prebble,W Y So,131.0,1158.0,10.0,-,1 1 1,0.56.90,6.8,2015-06-17,1,5,1000,GOOD TO FIRM,WANG TAK HANDICAP,TURF - C COURSE,575000,Happy Valley

# CAN ANYONE INVESTIGATE ON THIS?

In [3]:
# results['plc'] = results['plc'].apply(int)
results['plc'].unique()
# results.describe()

array(['1', '1 DH', '2', '2 DH', '3', '3 DH', '4', '4 DH', '5', '5 DH',
       '6', '6 DH', '7', 'WV', '7 DH', '8', '8 DH', '9', 'PU', '9 DH',
       '10', 'UR', 'WV-A', '11', 'FE', 'DNF', '12', 'WX', 'TNP', '13',
       nan, 'WX-A', '14'], dtype=object)

# Convert data into Date, Venue, Course, and Race No. level

In [4]:
text = 'NATURAL EIGHT(S243)'

pattern = re.compile(r'([\w\W]+)?([\(])([A-Z0-9]+)([\)])')

def extract_horse_code(pattern, text):
#     print(text)
    match = re.match(pattern, text)
    return match.group(3)

In [5]:
results['horse_code'] = results['horse'].apply(lambda x: extract_horse_code(pattern, x))
results.head()

,row,plc,horseno,horse,jockey,trainer,actualwt,declarwt,draw,lbw,runningpos,finishtime,winodds,date,raceno,class,distance,going,handicap,course,stake,venue,horse_code
0,0,1,10.0,NATURAL EIGHT(S243),C Y Ho,C Fownes,119.0,1037.0,1.0,-,4 3 1,1.10.19,3.5,2015-06-03,1,5,1200,GOOD TO FIRM,MOUNT BUTLER HANDICAP,TURF - A COURSE,575000,Happy Valley,S243
1,0,1,7.0,SOLAR HEI HEI(T242),B Prebble,D J Hall,125.0,1077.0,11.0,-,9 8 1,1.09.06,2.3,2015-06-07,1,4,1200,GOOD TO FIRM,HKU FOUNDATION HANDICAP,TURF - A+3 COURSE,760000,Sha Tin,T242
2,0,1,3.0,GRAN BOLIVAR(S165),H N Wong,Y S Tsui,121.0,950.0,9.0,-,1 1 1,1.09.64,32.0,2015-06-10,1,4,1200,GOOD TO FIRM,LAI ON HANDICAP,TURF - B COURSE,760000,Happy Valley,S165
3,0,1,11.0,PEOPLE'S KNIGHT(T305),G Mosse,J Moore,120.0,1149.0,4.0,-,4 4 1,1.09.70,6.6,2015-06-14,1,1,1200,GOOD TO FIRM,BREGUET PLATE,TURF - B+2 COURSE,800000,Sha Tin,T305
4,0,1,2.0,SIR JOHN(P344),B Prebble,W Y So,131.0,1158.0,10.0,-,1 1 1,0.56.90,6.8,2015-06-17,1,5,1000,GOOD TO FIRM,WANG TAK HANDICAP,TURF - C COURSE,575000,Happy Valley,P344

In [6]:
#results[results['raceno'] == 1].groupby(['course','raceno']).size()

# results[(results['raceno'] == 1) & (results['date'] == '2015-06-03')].groupby(['venue','course']).size()

results.groupby(['date','venue','course','raceno']).size()


results[(results['course'] == 'TURF - A COURSE') & (results['date'] == '2015-06-03') & (results['raceno'] == 2)]

,row,plc,horseno,horse,jockey,trainer,actualwt,declarwt,draw,lbw,runningpos,finishtime,winodds,date,raceno,class,distance,going,handicap,course,stake,venue,horse_code
118,0,1,5.0,ROBUST MOMENTUM(P422),C Y Ho,C Fownes,122.0,1209.0,1.0,-,2 3 2 1,1.40.18,2.5,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,P422
1232,1,2,1.0,AXIOM(P095),A Suborics,A Schutz,129.0,1088.0,12.0,1,10 10 9 2,1.40.34,82.0,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,P095
2346,2,3,11.0,LIGHTNING AND GOLD(P354),W M Lai,C H Yip,114.0,1034.0,11.0,1-1/4,11 11 10 3,1.40.38,27.0,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,P354
3460,3,4,7.0,CHINA DELIGHT(N148),T H So,K W Lui,121.0,1031.0,2.0,1-1/4,12 12 12 4,1.40.38,13.0,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,N148
4574,4,5,2.0,AMAZING ALWAYS(N432),D Whyte,D E Ferraris,125.0,1133.0,7.0,1-1/4,8 7 8 5,1.40.40,6.8,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,N432
5686,5,6,10.0,RED COURAGE(N110),K Teetan,J Size,117.0,1186.0,5.0,2,3 2 3 6,1.40.50,11.0,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,N110
6797,6,7,12.0,DRAGON GLORY(P130),M Chadwick,C W Chang,113.0,1156.0,3.0,2,4 6 4 7,1.40.51,10.0,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,P130
7900,7,8,3.0,CIRCUIT STAR(N220),K C Leung,K L Man,123.0,1054.0,9.0,2,7 8 7 8,1.40.52,30.0,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,N220
9001,8,9,4.0,MAC ROW(N252),M L Yeung,A Lee,122.0,1001.0,8.0,3-3/4,9 9 11 9,1.40.78,9.9,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,N252
10092,9,10,8.0,CONFUCIUS SPIRIT(S329),N Callan,S Woods,120.0,1088.0,4.0,5,6 5 6 10,1.40.98,10.0,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,S329
11166,10,11,6.0,SPIRIT SOARING(N099),N Rawiller,W Y So,124.0,1098.0,6.0,5-1/4,1 1 1 11,1.41.04,10.0,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,N099
12220,11,12,9.0,SOUTHERN SPRINGS(P139),H W Lai,C S Shum,118.0,1112.0,10.0,11-3/4,5 4 5 12,1.42.07,38.0,2015-06-03,2,4,1650,GOOD TO FIRM,MOUNT CAMERON HANDICAP,TURF - A COURSE,760000,Happy Valley,P139

In [7]:
results.groupby(['date','venue','course','raceno']).size().to_frame('count_horse').reset_index()

            date         venue             course  raceno  count_horse
0     2015-06-03  Happy Valley    TURF - A COURSE       1           12
1     2015-06-03  Happy Valley    TURF - A COURSE       2           12
2     2015-06-03  Happy Valley    TURF - A COURSE       3           12
3     2015-06-03  Happy Valley    TURF - A COURSE       4           12
4     2015-06-03  Happy Valley    TURF - A COURSE       5           12
5     2015-06-03  Happy Valley    TURF - A COURSE       6           12
6     2015-06-03  Happy Valley    TURF - A COURSE       7           13
7     2015-06-03  Happy Valley    TURF - A COURSE       8           13
8     2015-06-07       Sha Tin  ALL WEATHER TRACK       2           14
9     2015-06-07       Sha Tin  ALL WEATHER TRACK       5           13
10    2015-06-07       Sha Tin  ALL WEATHER TRACK       8           14
11    2015-06-07       Sha Tin  TURF - A+3 COURSE       1           16
12    2015-06-07       Sha Tin  TURF - A+3 COURSE       3           14
13    2015-06-07       Sha Tin  TURF - A+3 COURSE       4           14
14    2015-06-07       Sha Tin  TURF - A+3 COURSE       6           15
15    2015-06-07       Sha Tin  TURF - A+3 COURSE       7           10
16    2015-06-07       Sha Tin  TURF - A+3 COURSE       9           14
17    2015-06-07       Sha Tin  TURF - A+3 COURSE      10           14
18    2015-06-10  Happy Valley    TURF - B COURSE       1           12
19    2015-06-10  Happy Valley    TURF - B COURSE       2           12
20    2015-06-10  Happy Valley    TURF - B COURSE       3           11
21    2015-06-10  Happy Valley    TURF - B COURSE       4           12
22    2015-06-10  Happy Valley    TURF - B COURSE       5           12
23    2015-06-10  Happy Valley    TURF - B COURSE       6           12
24    2015-06-10  Happy Valley    TURF - B COURSE       7           12
25    2015-06-10  Happy Valley    TURF - B COURSE       8           12
26    2015-06-14       Sha Tin  TURF - B+2 COURSE       1           12
27    2015-06-14       Sha Tin  TURF - B+2 COURSE       2           14
28    2015-06-14       Sha Tin  TURF - B+2 COURSE       3           15
29    2015-06-14       Sha Tin  TURF - B+2 COURSE       4           12
...          ...           ...                ...     ...          ...
1084  2017-06-18       Sha Tin  TURF - C+3 COURSE       6            9
1085  2017-06-18       Sha Tin  TURF - C+3 COURSE       8           11
1086  2017-06-18       Sha Tin  TURF - C+3 COURSE       9           12
1087  2017-06-28  Happy Valley  TURF - C+3 COURSE       2           13
1088  2017-06-28  Happy Valley  TURF - C+3 COURSE       3           13
1089  2017-06-28  Happy Valley  TURF - C+3 COURSE       4           12
1090  2017-06-28  Happy Valley  TURF - C+3 COURSE       5           12
1091  2017-06-28  Happy Valley  TURF - C+3 COURSE       6           12
1092  2017-06-28  Happy Valley  TURF - C+3 COURSE       7           12
1093  2017-06-28  Happy Valley  TURF - C+3 COURSE       8           13
1094  2017-07-09       Sha Tin  ALL WEATHER TRACK       4           12
1095  2017-07-09       Sha Tin  ALL WEATHER TRACK       6           12
1096  2017-07-09       Sha Tin  ALL WEATHER TRACK       8           12
1097  2017-07-09       Sha Tin  TURF - B+2 COURSE       1            7
1098  2017-07-09       Sha Tin  TURF - B+2 COURSE       2           14
1099  2017-07-09       Sha Tin  TURF - B+2 COURSE       3           14
1100  2017-07-09       Sha Tin  TURF - B+2 COURSE       5           15
1101  2017-07-09       Sha Tin  TURF - B+2 COURSE       9           13
1102  2017-07-09       Sha Tin  TURF - B+2 COURSE      10           15
1103  2017-07-16       Sha Tin    TURF - C COURSE       1           13
1104  2017-07-16       Sha Tin    TURF - C COURSE       2           15
1105  2017-07-16       Sha Tin    TURF - C COURSE       3           14
1106  2017-07-16       Sha Tin    TURF - C COURSE       4           15
1107  2017-07-16       Sha Tin    TURF - C COURSE       5           14
1108  2017-07-16       Sha Tin    TURF - C COURSE       6           14
1109  2017-07-16       Sha Tin    TURF - C COURSE       7           15
1110  2017-07-16       Sha Tin    TURF - C COURSE       8            8
1111  2017-07-16       Sha Tin    TURF - C COURSE       9           15
1112  2017-07-16       Sha Tin    TURF - C COURSE      10           13
1113  2017-07-16       Sha Tin    TURF - C COURSE      11           14

[1114 rows x 5 columns]

In [8]:
results['trainer'].unique()

array(['C Fownes', 'D J Hall', 'Y S Tsui', 'J Moore', 'W Y So',
       'A Schutz', 'K W Lui', 'P F Yiu', 'T K Ng', 'D Cruz', 'C S Shum',
       'C H Yip', 'K L Man', 'A T Millard', 'C W Chang', 'J Size', 'L Ho',
       "P O'Sullivan", 'D E Ferraris', 'A Lee', 'A S Cruz', 'S Woods',
       'T P Yung', 'R Gibson', "A P O'Brien", 'N Hori', 'M Hawkes',
       'M Sakaguchi', 'A Fabre', 'M Saito', 'J Lau', 'de Royer Dupre',
       'H Fujiwara', 'M Delzangles', 'Y Ikee', 'R Okubo', 'G Enebish',
       'F Rohaut', 'T Tanaka', 'K Lees', 'C Appleby', 'A Bull',
       'G W Moore', 'C Waller', 'Barande-Barbe', 'H Otonashi',
       'S Kunieda', 'P B Shaw', 'W A Ward', 'Y C Fung', 'D A Hayes',
       'M F de Kock', 'K Yoshimura', 'M C Tam', 'K Fujioka', 'J M Moore',
       'Pat Lee', 'Sir M R Stoute', 'M L W Bell', 'E M Lynam',
       'G Portelli', 'R Hannon', 'P Bary', 'T Ozeki', "D O'Meara",
       'W H Tse', 'F Head', "J O'Shea", 'R Fahey', 'K C Chong',
       'D K Weld', 'C Clement', 'E Mader', 'R Heathcote', 'S H Cheong',
       'A de Watrigant', 'K C Wong'], dtype=object)

In [9]:
results['jockey'].unique()

array(['C Y Ho', 'B Prebble', 'H N Wong', 'G Mosse', 'J Moreira',
       'A Suborics', 'M L Yeung', 'N Rawiller', 'D Whyte', 'C Schofield',
       'Z Purton', 'K Teetan', 'G Benoist', 'N Callan', 'S de Sousa',
       'R Moore', 'Y T Cheng', 'T H So', 'O Doleuze', 'K K Chiong',
       'K C Leung', 'M Chadwick', 'C Williams', 'S Clipperton',
       'U Rispoli', 'A Sanna', 'W M Lai', 'C K Tong', 'H W Lai',
       'V Cheminaud', 'T Angland', 'O Bosson', 'M Guyon', 'H T Mo',
       'M F Poon', 'K C Ng', 'E da Silva', 'T Berry', 'A Badel', 'D Lane',
       'R Fourie', 'O Murphy', 'H Bowman', 'G Lerena', 'L Salles',
       'M Demuro', 'C Soumillon', 'Y Take', 'G Schofield', 'K Tosaki',
       'C Murray', 'F Geroux', 'D Oliver', 'M Barzalona', 'L Corrales',
       'P Smullen', 'C Brown', 'N Juglall', 'J McDonald', 'Y Iwata',
       'P-C Boudot', 'O Peslier', 'S Pasquier', 'H Lam', 'R Myers',
       'T Clark', 'S Hamanaka', 'M Ebina', 'Y Kawada', 'B Shinn',
       'B Vorster', 'J Rosario', 'W L Ho', 'C Perkins', "D O'Brien",
       'M Wepner', 'C F Wong', 'V Espinoza', 'C Hayes', 'B Melham',
       'J Doyle', 'R Curatolo', '---', 'D Tudhope', 'T Jarnet', 'G Lee',
       'D Browne', 'D Chong'], dtype=object)

In [10]:
df = pd.pivot_table(results,
               index = ['date','venue','course','raceno'],
               columns = ['draw'],
               values = ['horse_code'],#,'trainer','jockey'],
               aggfunc = max)

df.reset_index(inplace = True)

In [11]:
df = df.droplevel(1, axis = 1)
df.columns = ['date', 'venue', 'course', 'raceno', 'horse_1', 'horse_2', 'horse_3',
      'horse_4', 'horse_5', 'horse_6', 'horse_7', 'horse_8', 'horse_9', 'horse_10',
      'horse_11', 'horse_12', 'horse_13', 'horse_14']

In [12]:
df

,date,venue,course,raceno,horse_1,horse_2,horse_3,horse_4,horse_5,horse_6,horse_7,horse_8,horse_9,horse_10,horse_11,horse_12,horse_13,horse_14
0,2015-06-03,Happy Valley,TURF - A COURSE,1,S243,L251,N186,P331,P175,P204,S075,M406,M255,N359,S150,NaN,NaN,NaN
1,2015-06-03,Happy Valley,TURF - A COURSE,2,P422,N148,P130,S329,N110,N099,N432,N252,N220,P139,P354,P095,NaN,NaN
2,2015-06-03,Happy Valley,TURF - A COURSE,3,S445,N265,M273,N055,S086,P308,T072,P088,N134,N317,T133,T328,NaN,NaN
3,2015-06-03,Happy Valley,TURF - A COURSE,4,T163,S224,P213,S104,S349,N193,S330,S170,L136,S160,S295,N233,NaN,NaN
4,2015-06-03,Happy Valley,TURF - A COURSE,5,S137,P016,P371,P418,T069,S157,S254,P444,P064,N295,M026,S051,NaN,NaN
5,2015-06-03,Happy Valley,TURF - A COURSE,6,P396,S004,T037,P381,P416,T191,T196,S436,T123,P429,T201,P058,NaN,NaN
6,2015-06-03,Happy Valley,TURF - A COURSE,7,P309,P421,P145,N248,P008,N323,S412,P281,S100,M063,T145,P358,NaN,NaN
7,2015-06-03,Happy Valley,TURF - A COURSE,8,S156,S099,P254,N344,N253,N384,P149,P183,T187,S093,S162,N040,NaN,NaN
8,2015-06-07,Sha Tin,ALL WEATHER TRACK,2,M017,N070,P316,P430,P075,T040,S046,S175,P280,M152,P084,S369,S197,P073
9,2015-06-07,Sha Tin,ALL WEATHER TRACK,5,S237,T081,P170,L282,N218,P239,P156,N156,M326,T099,T260,S273,NaN,NaN
10,2015-06-07,Sha Tin,ALL WEATHER TRACK,8,P169,M376,P181,S066,S388,N014,M021,S023,S306,P425,T115,S234,N379,P184
11,2015-06-07,Sha Tin,TURF - A+3 COURSE,1,S397,P398,T177,P434,S450,P402,T175,N115,T025,T166,T242,T019,S323,T132
12,2015-06-07,Sha Tin,TURF - A+3 COURSE,3,T134,P112,S098,L379,S372,S070,N386,P424,T018,T064,S433,T057,T045,S387
13,2015-06-07,Sha Tin,TURF - A+3 COURSE,4,T014,S275,M339,S044,T093,T170,P111,S167,P038,M347,S415,N309,P414,S221
14,2015-06-07,Sha Tin,TURF - A+3 COURSE,6,P219,S218,P436,N291,N069,P376,T208,S241,T031,P119,P357,M154,P240,P279
15,2015-06-07,Sha Tin,TURF - A+3 COURSE,7,P262,P435,T188,S190,N369,T198,S194,T197,P146,NaN,NaN,NaN,NaN,NaN
16,2015-06-07,Sha Tin,TURF - A+3 COURSE,9,P297,S028,P229,T236,P171,S276,S308,S405,T256,T111,L247,S378,T286,P102
17,2015-06-07,Sha Tin,TURF - A+3 COURSE,10,S305,P178,S269,T296,T245,P263,T050,S317,S301,T211,S203,S014,T059,L363
18,2015-06-10,Happy Valley,TURF - B COURSE,1,P411,S336,P257,T084,N138,T183,S314,T024,S165,N142,L254,N407,NaN,NaN
19,2015-06-10,Happy Valley,TURF - B COURSE,2,M061,N166,P241,K318,S290,P449,M212,S214,P081,N254,N146,N271,NaN,NaN
20,2015-06-10,Happy Valley,TURF - B COURSE,3,N099,P035,P405,P198,N252,P272,P096,T002,P266,P397,N188,NaN,NaN,NaN
21,2015-06-10,Happy Valley,TURF - B COURSE,4,M329,T038,M350,S102,S073,M378,M250,S113,T035,T294,N275,S339,NaN,NaN
22,2015-06-10,Happy Valley,TURF - B COURSE,5,S172,P267,S216,N012,T016,T225,N387,N307,P223,T171,L401,S442,NaN,NaN
23,2015-06-10,Happy Valley,TURF - B COURSE,6,T095,M199,T189,P385,P355,P120,T312,S224,P287,T210,S316,T121,NaN,NaN
24,2015-06-10,Happy Valley,TURF - B COURSE,7,S242,T053,T224,T118,N401,T146,P428,P234,N436,N303,T017,S121,NaN,NaN
25,2015-06-10,Happy Valley,TURF - B COURSE,8,T200,S262,M085,N333,P278,N423,S280,S253,P018,S010,P416,P103,NaN,NaN
26,2015-06-14,Sha Tin,TURF - B+2 COURSE,1,T178,T108,T263,T305,T128,T280,T253,T279,T283,T106,T252,T324,NaN,NaN
27,2015-06-14,Sha Tin,TURF - B+2 COURSE,2,S320,S446,S365,P163,M406,S257,P168,L070,M305,P216,K019,N208,S201,P136
28,2015-06-14,Sha Tin,TURF - B+2 COURSE,3,P066,S019,P395,T216,T303,S385,T205,M326,S229,T135,T262,P387,T328,P299
29,2015-06-14,Sha Tin,TURF - B+2 COURSE,4,N090,P415,N013,P293,N263,S007,M377,P128,S026,S062,L393,S205,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1084,2017-06-18,Sha Tin,TURF - C+3 COURSE,6,V013,V184,V326,T145,S437,S266,S355,A201,V192,NaN,NaN,NaN,NaN,NaN
1085,2017-06-18,Sha Tin,TURF - C+3 COURSE,8,V235,A260,A244,V248,V068,A171,A216,A215,A253,V256,T419,NaN,NaN,NaN
1086,2017-06-18,Sha Tin,TURF - C+3 COURSE,9,V410,T305,T355,T342,T406,S332,A091,T087,A041,A024,V214,NaN,NaN,NaN
1087,2017-06-28,Happy Valley,TURF - C+3 COURSE,2,S138,T220,S439,T178,V212,S073,V260,V164,V276,V011,S218,S247,NaN,NaN
1088,2017-06-28,Happy Valley,TURF - C+3 COURSE,3,V302,V341,T333,T326,P099,N432,N177,P423,T059,NaN,T298,A063,NaN,NaN
1089,2017-06-28,Happy Valley,TURF - C+3 COURSE,4,S130,A059,A144,S399,T232,S291,V022,V074,A049,S324,V273,V401,NaN,NaN
1090,2017-06-28,Happy Valley,TURF - C+3 COURSE,5,P435,T210,S216,A195,V017,T248,A007,A163,P212,T427,V347,V200,NaN,NaN
1091,2017-06-28,Happy Valley,TURF - C+3 COURSE,6,V020,V288,S199,A218,T368,V279,T046,V131,T100,V016,T055,V081,NaN,NaN
1092,2017-06-28,Happy Valley,TURF - C+3 COURSE,7,S253,T193,V381,T379,V186,S332,S242,A066,S264,A134,S298,T151,NaN,NaN
1093,2017-06-28,Happy Valley,TURF - C+3 COURSE,8,V412,V229,A203,V235,P429,A064,V012,A305,S385,P106,P041,T024,NaN,NaN
1094,2017-07-09,Sha Tin,ALL WEATHER TRACK,4,V255,A270,T381,A185,S367,V182,S204,T359,A281,V226,A068,T073,NaN,NaN
1095,2017-07-09,Sha Tin,ALL WEATHER TRACK,6,V232,A097,S200,A294,V404,S054,A197,V368,V254,A100,V055,T010,NaN,NaN
1096,2017-07-09,Sha Tin,ALL WEATHER TRACK,8,V118,S442,T313,T248,T254,T334,A216,T392,V264,A011,V394,A022,NaN,NaN
1097,2017-07-09,Sha Tin,TURF - B+2 COURSE,1,A207,NaN,A301,NaN,NaN,A308,A200,A283,NaN,A271,A220,NaN,NaN,NaN
1098,2017-07-09,Sha Tin,TURF - B+2 COURSE,2,V215,T042,V091,N387,N186,S320,T258,T027,P295,V309,T259,T071,S070,S241
1099,2017-07-09,Sha Tin,TURF - B+2 COURSE,3,T332,T339,T380,A053,A081,A266,V087,A110,V123,T412,A018,S138,V301,T224
1100,2017-07-09,Sha Tin,TURF - B+2 COURSE,5,A221,A280,A039,V421,T099,S240,A177,T091,T226,V026,A130,A106,A047,A104
1101,2017-07-09,Sha Tin,TURF - B+2 COURSE,9,T114,T315,A214,V125,T197,A002,P230,V133,V246,T109,V184,A129,NaN,NaN
1102,2017-07-09,Sha Tin,TURF - B+2 COURSE,10,A247,T361,A137,T376,A050,A297,A218,A233,A196,T349,A131,T391,S420,V071
1103,2017-07-16,Sha Tin,TURF - C COURSE,1,T429,V108,P257,V252,T253,S441,P269,A012,T285,T280,T054,V283,NaN,NaN
1104,2017-07-16,Sha Tin,TURF - C COURSE,2,NaN,S205,V122,V406,S121,V159,P293,V091,T203,T019,P354,V354,S346,S446
1105,2017-07-16,Sha Tin,TURF - C COURSE,3,A266,P400,V088,A307,T289,V402,A128,T129,V130,V086,T031,V242,NaN,NaN
1106,2017-07-16,Sha Tin,TURF - C COURSE,4,T202,V157,V243,S106,V001,S138,A348,V207,T373,V171,A023,V022,A005,P272
1107,2017-07-16,Sha Tin,TURF - C COURSE,5,S414,V039,V244,P151,S147,S379,N248,V403,V263,T108,V213,T105,S388,S100
1108,2017-07-16,Sha Tin,TURF - C COURSE,6,NaN,S096,A222,A055,S098,A110,V102,T265,A027,A276,V205,S426,S278,A153
1109,2017-07-16,Sha Tin,TURF - C COURSE,7,S332,A096,A120,S312,V361,T376,T046,V321,T094,V381,A095,A135,A109,V192
1110,2017-07-16,Sha Tin,TURF - C COURSE,8,A066,T198,V397,P230,S393,V181,T118,A113,NaN,NaN,NaN,NaN,NaN,NaN
1111,2017-07-16,Sha Tin,TURF - C COURSE,9,A352,A139,P363,V040,A286,A164,A248,A168,A249,T117,S362,A232,A163,V176
1112,2017-07-16,Sha Tin,TURF - C COURSE,10,V118,P396,A337,V235,A006,V256,A217,A257,V250,S419,V379,A287,NaN,NaN
1113,2017-07-16,Sha Tin,TURF - C COURSE,11,S298,A098,V186,T371,S358,V214,V099,T375,V411,V372,A183,T396,T242,A041

In [13]:
win = pd.pivot_table(results[(results['plc'] == '1') | (results['plc'] == '1 DH')],
               index = ['date','venue','course','raceno'],
               values = ['draw'])

win = win.reset_index().rename(columns = {'draw':'draw_winner'})

## Extracting horse code from the horse name

## Import horse info file

In [14]:
horse_info = pd.read_csv('horse_info.csv', index_col = 0)

horse_info.head()

,horse,country,trainer,colour,sex,owner,import_type,current_rating,start_rating,sire,dam,age
0,()(S259),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(C368),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A BEAUTIFUL(T421),AUS,W Y So,Bay,Gelding,Sandia Yit Lau Ying Lam & Yit Kwok Leung,PP,64.0,58.0,Bushranger,Anfield,6.0
3,A FAST ONE(S424),AUS,D E Ferraris,Bay,Gelding,Samson Yip Yan Tion & David Vrijmoed,PPG,37.0,40.0,Holy Roman Emperor,Detail,6.0
4,A SHIN HIKARI(V614),JPN,NaN,Grey,Horse,Eishindo Co Ltd,VIS,NaN,NaN,Deep Impact,Catalina,NaN

## Extracting horse code from the horse name

In [15]:
horse_info['horse_code'] = horse_info['horse'].apply(lambda x: extract_horse_code(pattern, x))
horse_info.head()

,horse,country,trainer,colour,sex,owner,import_type,current_rating,start_rating,sire,dam,age,horse_code
0,()(S259),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S259
1,(C368),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C368
2,A BEAUTIFUL(T421),AUS,W Y So,Bay,Gelding,Sandia Yit Lau Ying Lam & Yit Kwok Leung,PP,64.0,58.0,Bushranger,Anfield,6.0,T421
3,A FAST ONE(S424),AUS,D E Ferraris,Bay,Gelding,Samson Yip Yan Tion & David Vrijmoed,PPG,37.0,40.0,Holy Roman Emperor,Detail,6.0,S424
4,A SHIN HIKARI(V614),JPN,NaN,Grey,Horse,Eishindo Co Ltd,VIS,NaN,NaN,Deep Impact,Catalina,NaN,V614

In [16]:
len(set(horse_info['horse_code']).intersection(set(results['horse_code'])))

1790

In [17]:
len(set(horse_info['horse_code']))

3935

In [18]:
len(set(results['horse_code']))

1807

In [19]:
horse_dim = horse_info[['horse_code','sex','country','age']]

horse_dim

     horse_code      sex country  age
0          S259      NaN     NaN  NaN
1          C368      NaN     NaN  NaN
2          T421  Gelding     AUS  6.0
3          S424  Gelding     AUS  6.0
4          V614    Horse     JPN  NaN
5          A181  Gelding     JPN  4.0
6          A259  Gelding     AUS  4.0
7          M275  Gelding     AUS  NaN
8          K175  Gelding      NZ  NaN
9          B068  Gelding     AUS  4.0
10         V136  Gelding     AUS  NaN
11         J308  Gelding     AUS  NaN
12         P303  Gelding     AUS  NaN
13         L290  Gelding      NZ  NaN
14         G108  Gelding      NZ  NaN
15         K210  Gelding     IRE  NaN
16         S446  Gelding      NZ  NaN
17         P265  Gelding     IRE  NaN
18         A328  Gelding     AUS  4.0
19         M284    Brown     IRE  NaN
20         L032  Gelding      NZ  NaN
21         P626    Brown      GB  NaN
22         T291  Gelding     IRE  NaN
23         P087  Gelding     AUS  NaN
24         A219  Gelding     AUS  NaN
25         T369  Gelding     IRE  6.0
26         T331  Gelding      GB  6.0
27         N260  Gelding     USA  NaN
28         V215  Gelding     AUS  6.0
29         M159  Gelding     IRE  NaN
...         ...      ...     ...  ...
3910       P015  Gelding     AUS  NaN
3911       V149  Gelding      NZ  6.0
3912       M361  Gelding      GB  NaN
3913       V386  Gelding     AUS  NaN
3914       P041  Gelding     IRE  NaN
3915       S288  Gelding     AUS  NaN
3916       T378  Gelding      NZ  6.0
3917       V116  Gelding      GB  5.0
3918       B292  Gelding      NZ  3.0
3919       M305  Gelding     AUS  NaN
3920       H071  Gelding     IRE  NaN
3921       B097     Colt      GB  4.0
3922       S435  Gelding      GB  NaN
3923       L074  Gelding     IRE  NaN
3924       N202  Gelding      NZ  NaN
3925       L416    Brown     AUS  NaN
3926       P077  Gelding      NZ  NaN
3927       T003  Gelding     AUS  NaN
3928       T258  Gelding      NZ  6.0
3929       L021  Gelding      NZ  NaN
3930       J184  Gelding      GB  NaN
3931       N146  Gelding     AUS  NaN
3932       M234  Gelding     USA  NaN
3933       N614    Horse     GER  NaN
3934       H285  Gelding      NZ  NaN
3935       S197  Gelding      FR  NaN
3936       A221  Gelding     AUS  4.0
3937       K180  Gelding      GB  NaN
3938       B113  Gelding      NZ  4.0
3939       V335  Gelding     GER  NaN

[3940 rows x 4 columns]

In [20]:
pd.get_dummies(horse_dim['sex'])

      Brown  Colt  Filly  Gelding  Grey  Horse  Mare  Rig  Roan
0         0     0      0        0     0      0     0    0     0
1         0     0      0        0     0      0     0    0     0
2         0     0      0        1     0      0     0    0     0
3         0     0      0        1     0      0     0    0     0
4         0     0      0        0     0      1     0    0     0
5         0     0      0        1     0      0     0    0     0
6         0     0      0        1     0      0     0    0     0
7         0     0      0        1     0      0     0    0     0
8         0     0      0        1     0      0     0    0     0
9         0     0      0        1     0      0     0    0     0
10        0     0      0        1     0      0     0    0     0
11        0     0      0        1     0      0     0    0     0
12        0     0      0        1     0      0     0    0     0
13        0     0      0        1     0      0     0    0     0
14        0     0      0        1     0      0     0    0     0
15        0     0      0        1     0      0     0    0     0
16        0     0      0        1     0      0     0    0     0
17        0     0      0        1     0      0     0    0     0
18        0     0      0        1     0      0     0    0     0
19        1     0      0        0     0      0     0    0     0
20        0     0      0        1     0      0     0    0     0
21        1     0      0        0     0      0     0    0     0
22        0     0      0        1     0      0     0    0     0
23        0     0      0        1     0      0     0    0     0
24        0     0      0        1     0      0     0    0     0
25        0     0      0        1     0      0     0    0     0
26        0     0      0        1     0      0     0    0     0
27        0     0      0        1     0      0     0    0     0
28        0     0      0        1     0      0     0    0     0
29        0     0      0        1     0      0     0    0     0
...     ...   ...    ...      ...   ...    ...   ...  ...   ...
3910      0     0      0        1     0      0     0    0     0
3911      0     0      0        1     0      0     0    0     0
3912      0     0      0        1     0      0     0    0     0
3913      0     0      0        1     0      0     0    0     0
3914      0     0      0        1     0      0     0    0     0
3915      0     0      0        1     0      0     0    0     0
3916      0     0      0        1     0      0     0    0     0
3917      0     0      0        1     0      0     0    0     0
3918      0     0      0        1     0      0     0    0     0
3919      0     0      0        1     0      0     0    0     0
3920      0     0      0        1     0      0     0    0     0
3921      0     1      0        0     0      0     0    0     0
3922      0     0      0        1     0      0     0    0     0
3923      0     0      0        1     0      0     0    0     0
3924      0     0      0        1     0      0     0    0     0
3925      1     0      0        0     0      0     0    0     0
3926      0     0      0        1     0      0     0    0     0
3927      0     0      0        1     0      0     0    0     0
3928      0     0      0        1     0      0     0    0     0
3929      0     0      0        1     0      0     0    0     0
3930      0     0      0        1     0      0     0    0     0
3931      0     0      0        1     0      0     0    0     0
3932      0     0      0        1     0      0     0    0     0
3933      0     0      0        0     0      1     0    0     0
3934      0     0      0        1     0      0     0    0     0
3935      0     0      0        1     0      0     0    0     0
3936      0     0      0        1     0      0     0    0     0
3937      0     0      0        1     0      0     0    0     0
3938      0     0      0        1     0      0     0    0     0
3939      0     0      0        1     0      0     0    0     0

[3940 rows x 9 columns]

In [21]:
horse_dim.describe()

               age
count  1153.000000
mean      4.932350
std       1.408285
min       2.000000
25%       4.000000
50%       5.000000
75%       6.000000
max      10.000000

## Create dataset for prediction

In [81]:
predmatrix = pd.merge(df, win
    , left_on = ['date','venue','course','raceno']
    , right_on = ['date','venue','course','raceno'])

## Dynamic data frame

In [141]:
len(predmatrix['date'].unique())

137

In [142]:

#jockey trainer to dictionaries
# jockeys = results['jockey'].unique()
# jockey_dict = {jockey: number for number, jockey in enumerate(set(jockeys))}
# trainers = results['trainer'].unique()
# trainer_dict = {trainer: number for number, trainer in enumerate(set(trainers))}

results_1 = results.copy()

# results_1['jockey'] = results_1['jockey'].apply(lambda x: str(jockey_dict[x]))
# results_1['trainer'] = results_1['trainer'].apply(lambda x: str(trainer_dict[x]))

# results_1['combination'] = results_1[['horse_code', 'jockey','trainer']].apply(lambda x: '_'.join(x), axis=1)
results_1 = results_1[results_1['plc'].notna()][results_1[results_1['plc'].notna()]['plc'].apply(lambda x: x.isnumeric())]
results_1['plc'] = results_1['plc'].apply(lambda x: int(x)) # ranking thing
#appearance
results_1['appearance']= results_1.groupby('horse_code').cumcount()
#count win so far
results_1['win_so_far'] = 0
results_1['top3_so_far'] = 0
winning_count = {}
top3_count = {}
for index, row in results_1.iterrows():
    if winning_count.get(row['horse_code']):
        results_1['win_so_far'].loc[index] = winning_count[row['horse_code']]
        if row['plc'] == 1:
            winning_count[row['horse_code']] += 1
    else:
        if row['plc'] == 1:
            winning_count[row['horse_code']] = 1
            
            
for index, row in results_1.iterrows():
    if top3_count.get(row['horse_code']):
        results_1['top3_so_far'].loc[index] = top3_count[row['horse_code']]
        if row['plc'] <= 3:
            top3_count[row['horse_code']] += 1
    else:
        if row['plc'] <=3:
            top3_count[row['horse_code']] = 1

#get info from horse info
info = horse_info.copy().set_index('horse_code')
def get_info(x):
    try:
        country = info.loc[x]['country']
    except:
        country = 'NA'
    try:
        colour = info.loc[x]['colour']
    except:
        colour = 'NA'
    try:
        sex = info.loc[x]['sex']
    except:
        sex = 'NA'
    try:
        age = info.loc[x]['age']
    except:
        age = 'NA'        
    return(country,colour,sex,age)
results_1['country'] = results_1['horse_code'].apply(lambda x: get_info(x)[0])
results_1['colour'] = results_1['horse_code'].apply(lambda x: get_info(x)[1])
results_1['sex'] = results_1['horse_code'].apply(lambda x: get_info(x)[2])
results_1['age'] = results_1['horse_code'].apply(lambda x: get_info(x)[3])

# results_2 = results_1[['date','combination','appearance','win_so_far','country','colour','sex','age']].set_index(['date','combination'])

In [143]:
results_2 = results_1[['date','horse_code','appearance','win_so_far','top3_so_far','class']]

In [144]:
results_2['class_change'] = results_2.groupby('horse_code')['class'].apply(pd.Series.diff)
results_2['win_rate'] = results_2['win_so_far']/results_2['appearance'] 
results_2['top3_rate'] = results_2['top3_so_far']/results_2['appearance']

C:\Users\Celes\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Celes\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Celes\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [145]:
no_horse = pd.DataFrame([['N/A','N/A','N/A','N/A']],columns = ['horse_code','sex','country','age'])

horse_dim = pd.concat([horse_dim,no_horse]).reset_index(drop = True)

In [146]:
results_2['win_rate_pct_change'] = results_2.groupby('horse_code')['win_rate'].apply(pd.Series.pct_change)
results_2['top3_pct_change'] = results_2.groupby('horse_code')['top3_rate'].apply(pd.Series.pct_change)

C:\Users\Celes\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Celes\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [147]:
horse_dynamic = results_2.copy()

horse_dynamic.fillna(0)

nohorse = pd.DataFrame([[date,0,0,0,0,0,0,0,0,0,0,0] for date in horse_dynamic['date'].unique()],columns = ['date', 'horse_code', 
                                                                                                            'appearance', 'win_so_far',
                                                                                                            'top3_so_far', 'age', 'class',
                                                                                                            'class_change', 'win_rate', 
                                                                                                            'top3_rate', 'win_rate_pct_change',
                                                                                                            'top3_pct_change'])
horse_dynamic = pd.concat([horse_dynamic,nohorse])